In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
#scipy패키지 optimizaiton,interpolation,미적분,fft : matlab

In [5]:
x = np.array([0.0,1.0,2.0,3.0,4.0,5.0])
y = np.array([0.0,0.8,0.9,0.1,-0.8,-1.0])

z = np.polyfit(x,y,3)

print(z)

p = np.poly1d(z)

[ 0.08703704 -0.81349206  1.69312169 -0.03968254]


In [6]:
p(0.5)

0.6143849206349201

# 상수 고려한 후 ? 달라지는 점과 reshape하는이유

# y와 w는?



In [12]:

from sklearn.datasets import make_regression
import statsmodels.api as sm

bias = 100

X0,y,w = make_regression(n_samples=200,n_features=1,bias=bias,noise=10,coef=True,random_state=1)
print(X0[:5,:])

X=sm.add_constant(X0)

print(X0[:5,:])

y=y.reshape(len(y),1)

w

[[ 0.23249456]
 [-0.03869551]
 [ 0.5505375 ]
 [ 0.50318481]
 [ 2.18697965]]
[[ 0.23249456]
 [-0.03869551]
 [ 0.5505375 ]
 [ 0.50318481]
 [ 2.18697965]]


array(86.44794301)