# 20190106  Numpy

20190106 NUMPY

수업 진행 순서 : 
numpy  -> pandas -> scipy,statsmodel -> scikits(machine learning) -> tensorflow(deep learning) -> keras(deep learning)


python 
list_연속적 메모리 공간자료 구조 앞뒤 데이터 주소 저장

###NUMPY###
*행 중심_ 이름별 점수 평균

numpy 배열(array) 
1차원 vector [1,2,3]_ 크기와 방향을 알아야한다
2차원 matrix  행열구조
3차원 tensor
=>배열을 선형대수 처리하기 위하여 

vector의 거리 : 두 벡터의 차에 루트 _ 피타고라스
vector의 방향 :내적
matrix : 여러개의 vector를 모아둔 것 _vector의 변환 
matrix @ matrix : 1)변환의 합 _ MRS(Move rocate scale)
                  2) 의사 결정시 ***특징 추출 *** eg) 4x5 @ 5x2 = 4x2
                 3) 시각화 할 시 : ***차원축소***  

#선형대수 : 선형으로 해결하자 -> 비선형도 잘게 나누면 선형

선형 변환
↓↓↓↓
scaling_ 대각선의 값이 크기를 결정
unequal scaling _
rotation_ 역/정방향 회전_ 2차원
horizontal shear
hyperbolic rotation


python 의  numpy 는 [자료구조 연산자 제어문 함수] 모두 가지고 있다
-> 언어라고 생각하면 됨 

numpy의 제어문에서 for 문 제거 _ 함수만 사용하면 처리할 수 있도록 (벡터의 연산)
=> 이러한 방법이 for문보다 100배 빠르다 ]

numpy -> 행중심 _ 검색할 때에는 이 방법이 ok

numpy는 동질적인 데이터만( 숫자면 숫자 , 문자면 문자 )


*numpy는 datatype(dtype)도 가지고 있다._ 대량의 데이터를 저장한다는 전제조건 *
INT8형 , INT 16 , INT 64형 (작은데이터를 저장할때에는 작은 데이터형 사용 )
shape
dimension


*numpy 는 연산자(universal function) 많이 보유 *

*행x열 곱에서는 앞뒤를 바꿀 수 없다 
eg) 4행 3열 * 3행 4열 = 4행 4열


###PANDAS(Panel+Analasis)###

열중심 처리 _ 과목 별로 평균

1차원 _ Series(동질 데이터)
2차원 _ Dataframe(이질 데이터)
3차원_Panel
*열 내 동질적,열간 이질적

###scipy,statsmodel ###
회귀분석과 상관분석으로 검증

 scipy,statsmodel -> Optimization(최적화), Interpolation(보관), Intergrate(적분) , Differential(미분)

*추정과 검정 *
↓↓↓↓↓↓
1.카이제곱
2.anorba(2개이상의 데이터)
3.marnoba(2개이상의 종속변수)
4.ankoba
5.mankoba


###sciktits(machine learning)####
model을 만드는 방법
↓↓↓↓↓↓
1.정보기반 학습 . Dicision Tree
random forest
adar boost
grand boost
xg boost

2.확률 기반 학습. Naive bayes
표준정규분포

3.유사도 기반 학습
vector가 표현하는 거리값, 방향 
가까운거리에 있는 것들은 같은 것으로 취급 
-피타고라스
유사도 기반  모델: Kmeans, KNN ,추천(데이터 기반 제품 추천 등+) 등

4.오차 기반 학습

선형회귀 ,상관분석
정규성 독립성 등


etc) 
*내적 사이각. 내적 유사도 *
***내적이 의미하는 바 알기 _ 두벡터의 사이각
코사인 유사도 


###cos / sin###
이세상의 모든 소리는 cos sin 그래프로 분리시켜 표현 가능
sin cos 합성하면 소리를 만들어 낼 수 있다

-각도 문제( radiant _호의 길이로 각도 표현-> 사람이 이름 이해하기위해 degree로 변경해준다(도) 
-주기 문제


#연립 방정식의 해 
계수들만 다 뽑는다 -> 행렬로 변환 -> 역행렬 해서 ~~
고유값 분해(정방행렬{행수와 열수가 같은것},대칭행렬에만적용),특이행렬 분해 
상관분석 , 공분산 , 상관계수


#고유값 분해(Principal component  analysis ,주성분 분석)
eg) 소리로 고장날 시기를 추측한다고 했을 때  들려오는 잡음을 제거하는 것이 주성분 분석 
고유vector 은 직교하는 축을 만들고 기존 데이터 재분석??????????

#svd는 희소행렬에 대하여 특징 추출 

#행열연산을 하는 이유는 특징추출

In [17]:
# flask
import flask #package _ 웹서버 기능 _ 5000번 포트로 서비스 

In [23]:
import matplotlib # 시각화 패키지 
import numpy as np  #별칭 class  
print(np.__version__) #넘파이가 가지고 있는 함수 호출 #__ __ 상위 오브젝트가 가진 속성
def pprint(arr):   #ndarray: numpy의 기본 데이터 타입
    print("type:{}".format(type(arr)))
    print("shape:{},dimension:{},dtype:{}".format(arr.shape,arr.ndim,arr.dtype))
    print("Array's Data:Wn",arr)
    
    #숫자의 default는 int 32형
arr = [1.0,2.0,3.0]#리스트
a = np.array([1,2,3]) #nd array 생성함수(매개변수:리스트) #초기화  #
pprint(a)

    

1.16.5
type:<class 'numpy.ndarray'>
shape:(3,),dimension:1,dtype:int32
Array's Data:Wn [1 2 3]


In [19]:
#인스턴스 상태 

a = np.array([0,1,2,3,4,5,6,7,8,9]) #ndarray  #ndarray와 np가 가진 명령 거의 동일 
print(id(a)) #python core 주소값 확인
print(a.size)#데이터 개수
print(a.astype(np.float32))#데이터 타입 변경, numpy 행중심, 동질적
print(a.dtype.itemsize*a.size) #전체 메모리 사이즈 (바이트)

#iterator  python 에서는 for in range 사용: list 생성
a= np.arange(1000)  #arange 는 ndarray 생성
a

1577804334224
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
40


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

# ndarray 

In [22]:
#ndarray 초기화 함수
print(np.zeros((3,4))) #0
print(np.ones((2,3,4),dtype=np.int16)) #1,3차원 면,행,열
print(np.full((2,2),7))  #2x2를 7로 채워라 
print(np.eye(4))  #대각행렬 identity _대각으로 전부 1   #행렬연산에서 항등원 
print(np.empty((4,2)))  #쓰레기 값 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 6.87739379e-321]
 [1.10343781e-312 8.70018274e-313]]


In [24]:
a= np.arange(0,100,10)  #ndarray  (처음값,끝값,중간값)
indices = [1,5,-1]  #list
print(indices)
b = a[indices] #리스트를 첨자로 사용
print(a)
print(b)

[1, 5, -1]
[ 0 10 20 30 40 50 60 70 80 90]
[10 50 90]


In [31]:
a = np.arange(11,36)
print(a) #1차원
a.shape=(5,5)  #5x5로 바꿔라  #갯수가 안맞으면 오류남 ( 5x5 = 25개)
print(a)
print(type(a)) 
print(a.dtype) #ndarray의 속성
print(a.shape) #차수 (5,5)
print(a.ndim)  #2차원
print(a.nbytes) #100바이트 = 25개*4바이트
print(a.strides) # (20,4) => 다음 행과 다음 열의 데이터는 몇바이트를 건너 뛰어야하는가 
                 #컴퓨터에는 데이터가 일렬로 쭉  되어있기 때문에

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
<class 'numpy.ndarray'>
int32
(5, 5)
2
100
(20, 4)


In [32]:
arr=np.arange(10) # 0~9
print(type(arr))
print(arr)
print(arr[5])  #indexing 
print(arr[5:8]) #마지막 불보험
arr[5:8]=12  #5에서 8까지 데이터 업데이트 
print(arr[1:6])

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 1  2  3  4 12]


In [36]:
#numpy 첨자 생략 불가  eg) R에서 [,4]
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0])  #행우선 
print(arr2d[0][2]) #0행 2열
print(arr2d[0,2])  #0행 2열
print(arr2d[:2]) #0,1행  #  : 앞에오면 처음부터 : 뒤에오면 끝까지 
print(arr2d[:2,1:])
print(arr2d[:,1:])  #모든행
print(arr2d[1,:2])
print(arr2d[2,:1])
arr2d[:2,:1]=0
arr2d[:2,:1]=0
print(arr2d)

[1 2 3]
3
3
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]
 [8 9]]
[4 5]
[7]
[[0 2 3]
 [0 5 6]
 [7 8 9]]


In [39]:
#사람이 데이터를 다루는 것은 입체로 하지만 실제 저장은 일렬로 한다
#행렬 연산에서 앞의 행렬열수와 뒤의 행렬의 행수를  일치 시켜야 행렬 곱이 가능
#행렬 곱에서 행렬 앞뒤로 바꾸면 안된다 

print("스트라이드의 값 :",np.ones((3,4,5),dtype=np.float64).strides)
(160,40,8) #단일 데이터 float 64 : 8바이트


스트라이드의 값 : (160, 40, 8)


(160, 40, 8)

In [55]:
#문제

arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])  #2면,2행,3열 
print(arr3d)
print()
print('첫면은', arr3d[0])  #0번면
print()
print('첫면 첫행은 =',arr3d[0][0])
print()
print('첫 요소는 = ',arr3d[0][0][0])
print()

#8을 출력하시오

arr3d[1][0][1]

#12를 출력하시오 
arr3d[1][1][2]



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

첫면은 [[1 2 3]
 [4 5 6]]

첫면 첫행은 = [1 2 3]

첫 요소는 =  1



12

# numpy 백업

In [54]:
old_values=arr3d  #파이썬에서의 대입 :  주소를 복사 
arr3d[0]=42
print("값의 변경 후 ")
print(arr3d)
print('이전 값으로 복구')
arr3d= old_values   #원본이 사라짐 _ 바꿔도 백업이 불가능함 _ 대입하면 주소가 복사되기 때문 
print(arr3d)


값의 변경 후 
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [56]:
#복구
old_values=arr3d.copy()  #복구가능한 함수 
arr3d[0]=42
print("값의 변경 후 ")
print(arr3d)
print('이전 값으로 복구')
arr3d= old_values   #복구가능 
print(arr3d)

값의 변경 후 
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [60]:
Z=np.arange(36)
Z=Z.reshape((6,6))  #6x6
print(Z)
print()
reshape2= Z.reshape((2,3,6))  #2면 3행 6열
print(reshape2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [65]:
arr=np.arange(32).reshape((8,4))
print(arr)
print()
print(arr[[1,5,7,2]]) #행중심 인덱싱 _행 뽑기
print()
print(arr[[-1,-5,-7,-2]]) #뒤에서부터 인덱싱
print()
print(arr[[1,5,7,2],[0,3,1,2]])  #앞괄호 와 뒷괄호 하나씩 매칭 _ 1행0열  5행3열
#fancy 인덱싱 
print(arr[[1,2,5,7]][:,[0,1,2,3]])  #먼저 1,2,5,7행을 뽑고/  그것에 대하여 행렬 인덱싱
print()
print(arr[[1,5,7,2]][:,[0,3,1,2]])
print()


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]

[ 4 23 29 10]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]



In [66]:
arr=[]
for i in range(6):
    ad=[]
    for j in range(6):
        ad.append(i*10+j)  #i*10+j가 위치를 찾을 때 쓰는 식
    arr.append(ad)
print(arr)
arr=np.array(arr)

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]


# 해당블락 추출

In [77]:

arr=np.array(arr).reshape((6,6))
print(arr)
#orange
print(' orange :', arr[[0,1,2,3,4],[1,2,3,4,5]])

#red
arr[[0,2,5],[2,2,2]]
arr[[0,1,2,3,4],[1,2,3,4,5]]


#blue
arr[3:6][:,[0,2,5]]

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
 orange : [[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
red : [ 2 22 52]


In [88]:
#빨간색
print(arr[[0,2,3,4,5],2])
print(arr[:,2])

#주황색
print(arr[0,[3,4]])


#연두색  #2,4행 뽑고 거기에 인덱싱
print(arr[[2,4]][:,[0,2,4]])

#청록
print(arr[4:][:,[4,5]])

[ 2 22 32 42 52]
[ 2 12 22 32 42 52]
[3 4]
[[20 22 24]
 [40 42 44]]
[[44 45]
 [54 55]]


In [95]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)
print()
v = np.array([1,0,1])
print(v)
print()
print('타일출력')
vv = np.tile(v,(4,1))  #v를 행으로 4번 열로 1번 _  타일처럼 !
print(vv) # 4x3
print()
y = x+vv  #배열연산 ( 요소별로 연산)
print(y)
print()
#배열연산 : 양쪽 차원이 일치해야함 
print(x+v)   #4x3 , 1x3 broadcasting :  찻수가 안맞지만  1x3을 4번 반복하여 이를 맞춰줌
x+3

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

타일출력
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [132]:
x = np.arange(6).reshape((3,2))
print('1',x)

print(x.T)
#거듭제곱(행열 곱)
#x@x #앞의 행열 열수와 뒤의 행열의 행수가 일치
#(3x2)@(2x3) 이라서 오류   
#(3x2)@(3x2) 로 뒷 행열 형태 바꿔주기 _ 전치행렬

print('결과',x@x.T)

print(np.transpose(x))

1 [[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]
결과 [[ 1  3  5]
 [ 3 13 23]
 [ 5 23 41]]
[[0 2 4]
 [1 3 5]]


In [110]:
arr = np.arange(24).reshape((2,3,4))  #2면 3행 4열  #index(0,1,2)
print(arr)
print("ㅇㅅㅇ")
print(arr.transpose((1,0,2)))  #index번호 /  면과 행을 바꿔라 -> # 3면 2행 4열
print(arr.transpose(0,2,1))   #2면 4행 3열

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
ㅇㅅㅇ
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


# Boolean Indexing I ( True/False) _ 자주 쓰임



In [133]:
names = np.array(['Seoul','Daejeon','chungju','seoul','chungju','daejeon','daejeon'])
data = np.random.randn(7,4)
print(data)
print('서울이냐',names=='Seoul') #1,0,0,0,0,0,0
print(data[names == 'Seoul']) #0번행 
print(data[names == 'Seoul',2:]) #첫번째 행중에서 2번째 열부터 끝까지
print(data[names == 'Seoul',3])  #첫번째행 3열
print(names != 'Seoul') #서울이 아닌것 #0,1,1,1,1,1,1
print(~(names=='Seoul')) #전체의 부정
mask=(names =='Seoul')|(names=='chungju')
print(mask)
print(data[mask])

[[-0.05327024  0.62128188  1.44504328  0.51089608]
 [-0.33415885 -2.06582844 -1.06211133  0.40326423]
 [-0.13473302  0.63476107  0.53870167 -0.94065908]
 [-0.3470325  -1.19315181 -1.35554542 -0.4441783 ]
 [-0.44544675 -1.33008419  0.6282063  -0.05220443]
 [-1.25626306 -0.53035894  1.13031821 -0.6784283 ]
 [ 0.69014083  1.20264523  1.14386642 -1.17951828]]
서울이냐 [ True False False False False False False]
[[-0.05327024  0.62128188  1.44504328  0.51089608]]
[[1.44504328 0.51089608]]
[0.51089608]
[False  True  True  True  True  True  True]
[False  True  True  True  True  True  True]
[ True False  True False  True False False]
[[-0.05327024  0.62128188  1.44504328  0.51089608]
 [-0.13473302  0.63476107  0.53870167 -0.94065908]
 [-0.44544675 -1.33008419  0.6282063  -0.05220443]]


In [126]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])
print(zip(xarr,yarr,cond)) # zip : 요소별 데이터를 묶는 것 _ zip은 출력 불가 
print(list(zip(xarr,yarr,cond)))   #list로 바꿔서 !
result = [( x if c else y)for x,y,c in zip (xarr,yarr,cond)]  #3항 연산자 

print('result =',result)


#numpy 제공 where 문

result = np.where(cond,xarr,yarr)  #참이면 x값 거짓이면 y값
print(result)

arr= np.random.randn(4,4)
print(arr)
print(np.where(arr>0,2,-2))

[(1.1, 2.1, True), (1.2, 2.2, False), (1.3, 2.3, True), (1.4, 2.4, True), (1.5, 2.5, False)]
result = [1.1, 2.2, 1.3, 1.4, 2.5]
[1.1 2.2 1.3 1.4 2.5]
[[-1.24661291  0.16305043  0.74820164  1.88582977]
 [-1.00582857  0.68483968 -0.03481266 -1.31011227]
 [-2.51600604  1.00860683 -0.10181619 -0.97829697]
 [ 0.05264737 -2.32042525 -0.84085195 -0.4917549 ]]
[[-2  2  2  2]
 [-2  2 -2 -2]
 [-2  2 -2 -2]
 [ 2 -2 -2 -2]]


In [ ]:
#문제 ) 
#다음 데이터를 이용하여 두개다 참일때는0,cond1이 참일 때는 1. cond2가 참일 때는 2
#그 외일 때는 3으로 처리하여 출력하시오 

In [143]:
result=[]
cond1 = np.array([1,0,1,1,0,0,1],dtype = bool)

cond2 = np.array([0,1,1,1,0,1,1],dtype = bool)



for i in range(len(cond1)):
    if (cond1[i] and cond2[i]):
        result.append(0)    
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)
print('조건문',result)        

result1 = np.where(cond1&cond2,0,np.where(cond1,1,np.where(cond2,2,3))) 

print('3항 연산자',result1)


result2 = 1*(cond1&~cond2) +2*(cond2 & ~cond1) + 3* ~(cond1|cond2)
print('수식을 이용한',result2)

조건문 [1, 2, 0, 0, 3, 2, 0]
3항 연산자 [1 2 0 0 3 2 0]
수식을 이용한 [1 2 0 0 3 2 0]


In [146]:
x = np.arange(1,10001)
y = np.arange(10001,20001)

print(y)

z= np.zeros_like(x)  #다른 행렬과 같은 사이즈로 초기화
for i in range(10000):
    z[i]=x[i]+y[i]

[10001 10002 10003 ... 19998 19999 20000]


In [147]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4]) 
print(np.all(a==b))  #전체가 참일 때 참
print(np.exp(a)) #하나라도 참이면 참
print(np.exp(a)) #지수함수(자연대수 : 2.718) _ y값을 모를 때 스는 explonent

False
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
#선형대수 : 선형으로 해결하자 -> 비선형도 잘게 나누면 선형

# 행렬의 종류


In [ ]:
# 정방행렬 : 정사각형 (행과 열의 수가 같은 행렬)
# 대칭행렬 : 우상단과 좌하단이 같은 행렬 _ 거리값행렬,공분행렬,상관행렬 모두 대칭
# 대각행렬 : 대각은 scale 을 변화시키는 요소이다
# 단위행렬(identity) : 행렬 곱의 항등원  # 행렬과 역행렬을 곱하면 단위행렬( 기존 행렬 x 기존의 행렬의 분수 )
# 역행렬 : 행렬의 나눗셈을 위해, 구해서 곱해지는 행렬  ( 역행렬은 정방행렬만 가능하다.)
# 특이행렬 : 역행렬이 없는 행렬
# 직교행렬 : 축의 정직교 , 각 축간의 내적이 0인 행렬 
# 정방행렬이면서 대칭행렬 : 공분산행렬, 상관게수행렬, 거리행렬
# 공분산 : 두수간의 관계 . ((숫자:A-평균) * (숫자:B -평균))/ (n-1)
# 상관계수(표준화 : -1 ~ +1 사이의 수) : 공분산 / 표준편차의 곱 

In [153]:
import  numpy as np
F1 = np.array([[1,2],[3,4]])
F2 = np.array([[2,2],[2,2]])

print(F1)
print()
print(F2)
print()

print(F1 + F2) #요소끼리
print()
print(F1 * F2)
print()
print(F1 @ F2) #행열곱도 내적 _ 곱해서 더함 _ 두벡터의 사이각을 구해 차원 확장


#차원 축소나 확장은 순차적으로 이루어져야한다 _ 한꺼번에 이루어질 경우 데이터 손실 가능성 有

[[1 2]
 [3 4]]

[[2 2]
 [2 2]]

[[3 4]
 [5 6]]

[[2 4]
 [6 8]]

[[ 6  6]
 [14 14]]


# 방정식

#방정식의 해

2 X1 + X2 -2 X3 = -3
3 X1 +       X3 = 5 
X1  + X2 - X3   =-2

In [155]:
# X1 X2 X3 게수를 뽑아 온 것이 A

A= np.array([[2,1,-2],[3,0,1],[1,1,-1]])
print(A)
b = np.transpose(np.array([[-3,5,-2]])) #열로 전치
print(b
      
#solve 방법1     
x= np.linalg.solve(A,b) #A의 역행렬을 구해서 b와 곱해줌
#print(x)

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
[[-3]
 [ 5]
 [-2]]
[[ 1.]
 [-1.]
 [ 2.]]


In [156]:
#dot 방법2

np.dot(np.linalg.inv(A),b)  #행렬곱  #inv 는  역행렬 구해주는 함수 

array([[ 1.],
       [-1.],
       [ 2.]])

In [157]:
#방법3

np.linalg.inv(A)@b   #왜역행렬을 구해야하는가 ? 행렬은 나눗셈이 없어서 역행렬 곱해서 처리 

array([[ 1.],
       [-1.],
       [ 2.]])

In [159]:
#검산 

2*1 + (-1) -2*2

-3

In [160]:
a = np.array([0,1,0]) #y 축
b = np.array([1,0,0]) #x 축
res = np.dot(a,b)  #내적 사이각  0 도 나옴 => 직각
print(res)

0


In [163]:
print(np.linalg.norm(a)) # norm :벡터의 크기 
print(np.linalg.norm(b))
print(np.linalg.norm(a) * np.linalg.norm(b))
rad = res / (np.linalg.norm(a) * np.linalg.norm(b)) #cos(theta)
print('cos theta', rad)
print(np.arccos(rad)) #theta 값을 구함
print(np.degrees(np.arccos(rad))) #사람이 알아보는 각도로 표현 

1.0
1.0
1.0
cos theta 0.0
1.5707963267948966
90.0


In [165]:
x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)
print(x)
print(y)
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


#다음 방정식의 해를 구하고 검산하시오

x + y + z = 6
2y +5z = -4
2x  + 5y -z = 27

In [180]:
t = np.array([[1,1,1],[0,2,5],[2,5,-1]])
print(t)
i = np.transpose(np.array([[6,-4,27]]))
print(i)

#방법 1 

x = np.linalg.solve(t,i)
print(x)

#방법 2
x1 = np.dot(np.linalg.inv(t),i) 
print(x1)
#방법 3
x3 =np.linalg.inv(t)@i 
print(x3)

[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
[[ 6]
 [-4]
 [27]]
[[ 5.]
 [ 3.]
 [-2.]]
[[ 5.]
 [ 3.]
 [-2.]]
[[ 5.]
 [ 3.]
 [-2.]]


In [178]:
#검산 

5+3+(-2)

6