# modeling

https://books.google.co.kr/books?id=LTJFDwAAQBAJ&pg=PA134&lpg=PA134&dq=%ED%9D%91%EB%B0%B1%EC%9D%B4%EB%AF%B8%EC%A7%80+%EB%94%A5%EB%9F%AC%EB%8B%9D&source=bl&ots=m58eyFkxQ_&sig=ACfU3U3EGkypUS-G3t6amZqMp0Pvwit8Fg&hl=ko&sa=X&ved=2ahUKEwi2g-i5_drnAhWU7WEKHbApDHwQ6AEwCHoECAkQAQ#v=onepage&q=%ED%9D%91%EB%B0%B1%EC%9D%B4%EB%AF%B8%EC%A7%80%20%EB%94%A5%EB%9F%AC%EB%8B%9D&f=false

In [2]:

image_dir = './emotion_edit/'
afraid_dir= "./emotion_edit/afraid/"
anger_dir = "./emotion_edit/anger/"
disgusted_dir = "./emotion_edit/disgusted/"
happy_dir = "./emotion_edit/happy/"
neutral_dir = "./emotion_edit/neutral/"
sad_dir = "./emotion_edit/sad/"
surprised_dir = "./emotion_edit/surprised/"

In [3]:
from PIL import Image
import os,glob,numpy as np
from sklearn.model_selection import train_test_split
import numpy as np
from numpy import array
import cv2
image_path  = image_dir

category = ['afraid','anger','disgusted','happy','neutral','sad','surprised']
print(category)

n_class = len(category)
print(n_class)

['afraid', 'anger', 'disgusted', 'happy', 'neutral', 'sad', 'surprised']
7


In [4]:

X=[]
Y=[]
image_w =128
image_h =128
# pixels = image_w * image_h * 1

In [5]:
for idx, expression  in enumerate(category):
    label =[0 for i in range(n_class)] #라벨 초기화 
    label[idx]=1
    image_path = image_dir+'/'+ expression
    files = glob.glob(image_path+'/*.jpg')
    
    
    for i,f in enumerate(files):
        img = Image.open(f)
        img = img.convert('L') 
        img = img.resize((image_w, image_h))
        data = np.asarray(img)
        
        X.append(data)
        Y.append(label)
        
X = np.array(X)
Y=  np.array(Y)

In [6]:
print(X.shape)

(58875, 128, 128)


In [7]:
X_train, X_test, y_train,y_test = train_test_split(X,Y)
print(len(X))
print(len(Y))
print(len(X_train))
print(len(X_test))

58875
58875
44156
14719


In [8]:
print(X_train.shape)
print(X_train.shape[0])
print(X_test.shape)
print(y_train[:10])

(44156, 128, 128)
44156
(14719, 128, 128)
[[0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0]]


In [9]:
import tensorflow as tf

config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config)

In [10]:
X_train = X_train.astype(float)/255
X_test = X_test.astype(float)/255

In [11]:

import tensorflow as tf
from keras.applications import VGG16

Using TensorFlow backend.


In [12]:
import os,glob,numpy as np
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Dense,Flatten,Dropout
from keras.callbacks import EarlyStopping,ModelCheckpoint
import matplotlib.pyplot as plt
import keras.backend.tensorflow_backend as K

from keras import models, layers
from keras import Input
from keras.models import Model
from keras import optimizers, initializers, regularizers, metrics
from keras.callbacks import ModelCheckpoint
import os
from glob import glob
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
import math

from keras.models import Sequential
from keras import models
from keras import layers
from keras import optimizers,initializers,regularizers,metrics

##  MAX POOLING

In [13]:
img_row = 128
img_col = 128
channel =1
n_class = 7
batch_size =32
n_epoch =32
verbose =1
validation_split =0.2
learning_rate = 0.01


In [14]:
X_train = X_train.reshape(X_train.shape[0],128,128,1)
X_test = X_test.reshape(X_test.shape[0],128,128,1)

In [15]:
X_train.shape

(44156, 128, 128, 1)

In [16]:
model =Sequential()
#1
model.add(Conv2D(256,(3,3), padding ='same',input_shape =(img_row,img_col,channel),activation = 'relu'))
model.add(Conv2D(64,(3,3),activation ='relu',padding='same'))
# model.add(MaxPooling2D(2,2),strides=(2,2))
model.add(MaxPooling2D(2,2))
#2

model.add(Conv2D(128,(3,3),activation ='relu',padding='same'))
model.add(Conv2D(128,(3,3),activation ='relu',padding='same'))
# model.add(MaxPooling2D(2,2),strides=(2,2))
model.add(MaxPooling2D(2,2))
#3
model.add(Conv2D(256,(3,3),activation ='relu',padding='same'))
model.add(Conv2D(256,(3,3),activation ='relu',padding='same'))
model.add(Conv2D(256,(3,3),activation ='relu',padding='same'))
# model.add(MaxPooling2D(2,2),stride=(2,2))
model.add(MaxPooling2D(2,2))


#4

model.add(Conv2D(512,(3,3),activation ='relu',padding='same'))
model.add(Conv2D(512,(3,3),activation ='relu',padding='same'))
model.add(Conv2D(512,(3,3),activation ='relu',padding='same'))
# model.add(MaxPooling2D(2,2),stride=(2,2))
model.add(MaxPooling2D(2,2))

#5

model.add(Conv2D(512,(3,3),activation ='relu',padding='same'))
model.add(Conv2D(512,(3,3),activation ='relu',padding='same'))
model.add(Conv2D(512,(3,3),activation ='relu',padding='same'))
# model.add(MaxPooling2D(2,2),stride=(2,2))
model.add(MaxPooling2D(2,2))



#Flatten
model.add(layers.Flatten())
model.add(layers.Dense(4096,activation = 'relu'))
model.add(Dropout(0.5))
# model.add(layers.Dense(4096,activation ='relu'))
model.add(layers.Dense(2048,activation ='relu'))
model.add(layers.Dense(1024,activation ='relu'))
model.add(layers.Dense(n_class,activation ='softmax'))
# model.add(layers.Dense(7,activation = 'softmax'))



In [19]:
print(X_train.shape)

(44156, 128, 128, 1)


In [20]:
from keras.models import Sequential
from keras import models
from keras import layers
from keras import optimizers,initializers,regularizers,metrics

 # 보류
face_model = models.Sequential()
face_model.add(prevgg)
face_model.add(layers.Flatten())
face_model.add(layers.Dense(4096,activation = 'relu'))
face_model.add(layers.Dense(2048,activation ='relu'))
face_model.add(layers.Dense(1024,activation ='relu'))
face_model.add(layers.Dense(7,activation = 'softmax'))

In [21]:
model_dir = 'emotion_edit/model'
model_path = model_dir +'vgg16max.model'

In [22]:
checkpoint = ModelCheckpoint(filepath=model_path , monitor='val_loss', verbose=1, save_best_only=True)
early_stopping = EarlyStopping(monitor='val_loss', patience=6)
model.compile(loss='categorical_crossentropy', optimizer=optimizers.RMSprop(lr=2e-5), metrics=['acc'])

In [ ]:
maxmodel = model.fit(X_train,y_train,batch_size = batch_size,epochs = n_epoch,verbose=1,
                     validation_split =validation_split,callbacks=[checkpoint,early_stopping])


Train on 35324 samples, validate on 8832 samples
Epoch 1/32
 4384/35324 [==>...........................] - ETA: 3:10:35 - loss: 1.9457 - acc: 0.1510

## 모델 저장

In [ ]:
from keras.models import load_model
model.save('maxmodel.h5')

## 시각화

In [ ]:
import matplotlib.pyploy as plt
fig,loss = plt.subplots()
acc = loss.twinx()

loss.plot(maxmodel.maxmodel['loss'],'b',label ='train loss')
loss.plot(maxmodel.maxmoodel['val_loss'],'r',label ='val loss')
loss.set_xlabel('epoch')
loss.set_ylabel('loss')
loss.legend(;oc = 'upper right')


acc.plot(maxmodel.maxmodel['accuracy'],'y',label = 'train acc')
acc.plot(maxmodel.maxmodel['val_accuracy'],'g',label = 'val acc')
acc.set_ylabel('accuracy')
acc.legen(loc ='upper left')

plt.show()

## 실제그림 넣고 예측하기 

In [ ]:
from PIL import Image
import os,glob,numpy as np
from keras.models import load_model

In [ ]:
test_dir = '사진경로'
image_w =128
image_h =128

In [ ]:
X = []
filename =[]
files = glob.glob(test_dir + '/*.*')

In [ ]:
for i,f in enumerate(files):
    img = Image.open(f)
    img = img.convert("L")
    img = img.resize((image_w, image_h))
    data = np.asarray(img)
    filenames.append(f)
    
    X.append(data)

X= np.array(X)
model = load_model("./model/multi_img_classification.model") 

In [ ]:
#X_train = X_train.astype(float)/255
#X_test = X_test.astype(float)/ 255

In [ ]:
prediction = model.predict(X)

In [ ]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)}) #>> 넘파이 출력옵션 변경하는것! (소수점3자리까지)
cnt = 0
for i in prediction:
    pre_ans = i.argmax()  # 예측 레이블  # argmax : 함수를 최대로 만들기 위한 x 값 --> 즉 첫번째에서는 3번째만 1이므로 2가 출력됨
    print(i)
    print(pre_ans)
    pre_ans_str = ''
    if pre_ans == 0: pre_ans_str = "afraid"
    elif pre_ans == 1: pre_ans_str = "anger"
    elif pre_ans == 2: pre_ans_str = "disgusted"
    elif pre_ans == 3: pre_ans_str = "happy"
    elif pre_ans == 4: pre_ans_str = "neutral"
    elif pre_ans == 5: pre_ans_str = "sad"
    elif pre_ans == 6: pre_ans_str = "surprised"
    else: pre_ans_str = "스티로품"
    if i[0] >= 0.8 : print("해당 "+filenames[cnt].split("\\")[1]+"이미지는 "+pre_ans_str+"한 기분으로 추정됩니다.")
    if i[1] >= 0.8: print("해당 "+filenames[cnt].split("\\")[1]+"이미지는 "+pre_ans_str+"한 기분으로 추정됩니다.")
    if i[2] >= 0.8: print("해당 "+filenames[cnt].split("\\")[1]+"이미지는 "+pre_ans_str+"한 기분으로 추정됩니다.")
    if i[3] >= 0.8: print("해당 "+filenames[cnt].split("\\")[1]+"이미지는 "+pre_ans_str+"한 기분으로 추정됩니다.")
    if i[4] >= 0.8: print("해당 "+filenames[cnt].split("\\")[1]+"이미지는 "+pre_ans_str+"한 기분으로 추정됩니다.")
    if i[5] >= 0.8: print("해당 "+filenames[cnt].split("\\")[1]+"이미지는 "+pre_ans_str+"한 기분으로 추정됩니다.")
    if i[3] >= 0.8: print("해당 "+filenames[cnt].split("\\")[1]+"이미지는 "+pre_ans_str+"한 기분으로 추정됩니다.")    
    cnt += 1

## AVERAGE POOLING or avg로 해보기

- keras.layers.AveragePooling2D(pool_size=(2, 2), strides=None, padding='valid', data_format=None)

In [ ]:
from keras.layers import AveragePooling2D

In [ ]:
img_row = 128
img_col =128
channel =1
n_class = 7
batch_size =32
n_epoch =32


In [ ]:
model =Sequential()
#1
model.add(Conv2D(256,kernel =3, padding ='same',input_shape =(img_row,img_col,channel),activation = 'relu'))
model.add(Conv2D(64,(3,3),activation ='relu',padding='same'))
model.add(Maxpooling2D(2,2),strides=(2,2))

#2

model.add(Conv2D(128,(3,3),activation ='relu',padding='same'))
model.add(Conv2D(128,(3,3),activation ='relu',padding='same'))
model.add(AveragePooling2D(2,2),strides=(2,2))

#3
model.add(Conv2D(256,(3,3),activation ='relu',padding='same'))
model.add(Conv2D(256,(3,3),activation ='relu',padding='same'))
model.add(Conv2D(256,(3,3),activation ='relu',padding='same'))
model.add(AveragePooling2D(2,2),strides=(2,2))


#4

model.add(Conv2D(512,(3,3),activation ='relu',padding='same'))
model.add(Conv2D(512,(3,3),activation ='relu',padding='same'))
model.add(Conv2D(512,(3,3),activation ='relu',padding='same'))
model.add(AveragePooling2D(2,2),strides=(2,2))


#5

model.add(Conv2D(512,(3,3),activation ='relu',padding='same'))
model.add(Conv2D(512,(3,3),activation ='relu',padding='same'))
model.add(Conv2D(512,(3,3),activation ='relu',padding='same'))
model.add(AveragePooling2D(2,2),strides=(2,2))



#Flatten
model.add(layers.Flatten())
model.add(layers.Dense(4096,activation = 'relu'))
model.add(layers.Dense(4096,activation ='relu'))
model.add(layers.Dense(2048,activation ='relu'))
model.add(layers.Dense(1024,activation ='relu'))
model.add(layers.Dense(n_class,activation ='softmax'))
# model.add(layers.Dense(7,activation = 'softmax'))



In [ ]:
print(X_train.shape)

In [ ]:

model_dir = 'emotion_edit/model'
model_path = model_dir +'vgg16avg.model'

In [ ]:
checkpoint = ModelCheckpoint(filepath=model_path , monitor='val_loss', verbose=1, save_best_only=True)
early_stopping = EarlyStopping(monitor='val_loss', patience=6)
face_model.compile(loss='categorical_crossentropy', optimizer=optimizers.RMSprop(lr=2e-5), metrics=['acc'])

In [ ]:
avgmodel = model.fit(X_train,y_train,validation_split =validation_split, batch_size = batch_size , epochs = n_epoch , callbacks[checkpoint,early_stopping])

In [ ]:
from keras.models import load_model
model.save('avgmodel.h5')